// Autogenerated by Copilot, Need REVIEW
use std::ops::{Add, Div, Mul, Neg, Sub};

use ndarray::{ScalarOperand, prelude::*};
use ndarray_linalg::{Lapack, Norm, QR, SVD, Scalar};
use ndarray_rand::{RandomExt, rand_distr::Uniform};
use rand::distr::uniform::SampleUniform;

use crate::manifolds::Manifold;
use crate::utils::traits::{Real, Vector};
use crate::utils::{
    inner_product::InnerProduct,
    random_point::RandomPoint,
    tools::{get_scalar_from_float, qr, tsvd},
};

#[derive(Debug, Clone)]
pub enum PointType<D> {
    Factorized {
        u: Array2<D>,
        s: Array1<D>,
        vt: Array2<D>,
    },
    Full(Array2<D>),
}

#[derive(Debug, Clone)]
pub enum TangentVectorType<D> {
    Factorized {
        up: Array2<D>,
        m: Array2<D>,
        vp: Array2<D>,
    },
    Full(Array2<D>),
}

impl<D> Add for TangentVectorType<D>
where
    D: Real,
{
    type Output = Self;

    fn add(self, other: Self) -> Self {
        panic!("Do not directly add tangent vectors. Use the manifold's vector addition instead.")
    }
}

impl<'a, D> Add<&'a TangentVectorType<D>> for &'a TangentVectorType<D>
where
    D: Real,
{
    type Output = TangentVectorType<D>;

    fn add(self, other: &'a TangentVectorType<D>) -> TangentVectorType<D> {
        let _ = (self, other);
        panic!("Do not directly add tangent vectors. Use the manifold's vector addition instead.")
    }
}

impl<'a, D> Add<TangentVectorType<D>> for &'a TangentVectorType<D>
where
    D: Real,
{
    type Output = TangentVectorType<D>;

    fn add(self, other: TangentVectorType<D>) -> TangentVectorType<D> {
        let _ = (self, other);
        panic!("Do not directly add tangent vectors. Use the manifold's vector addition instead.")
    }
}

impl<D> Sub for TangentVectorType<D>
where
    D: Real,
{
    type Output = Self;

    fn sub(self, other: Self) -> Self {
        panic!(
            "Do not directly subtract tangent vectors. Use the manifold's vector subtraction instead."
        )
    }
}

impl<D> Mul<D> for TangentVectorType<D>
where
    D: Real,
{
    type Output = Self;

    fn mul(self, _rhs: D) -> Self {
        panic!(
            "Do not directly scale tangent vectors. Use the manifold's scalar multiplication instead."
        )
    }
}

impl<D> Div<D> for TangentVectorType<D>
where
    D: Real,
{
    type Output = Self;

    fn div(self, _rhs: D) -> Self {
        panic!("Do not directly scale tangent vectors. Use the manifold's scalar division instead.")
    }
}

impl<D> Neg for TangentVectorType<D>
where
    D: Real,
{
    type Output = Self;

    fn neg(self) -> Self {
        match self {
            TangentVectorType::Factorized { up, m, vp } => TangentVectorType::Factorized {
                up: -up,
                m: -m,
                vp: -vp,
            },
            TangentVectorType::Full(z) => TangentVectorType::Full(-z),
        }
    }
}

impl<D> Vector for TangentVectorType<D>
where
    D: Real,
{
    type Field = D;

    fn sum(&self) -> Self::Field {
        match self {
            TangentVectorType::Factorized { up, m, vp } => up.sum() + m.sum() + vp.sum(),
            TangentVectorType::Full(z) => z.sum(),
        }
    }

    fn zeros() -> Self {
        todo!()
    }

    fn add_refs(_lhs: &Self, _rhs: &Self) -> Self {
        panic!("Do not directly add tangent vectors. Use the manifold's vector addition instead.")
    }
}

#[derive(Debug, Clone)]
pub enum AmbientType<D> {
    Full(Array2<D>),
    // Represents Z = U @ S @ V.t()
    Factorized {
        u: Array2<D>,
        s: Array2<D>,
        v: Array2<D>,
    },
}

#[derive(Debug, Clone)]
pub struct FixedRank<D>
where
    D: Real,
{
    name: String,
    m: usize,
    n: usize,
    r: usize,
    _marker: std::marker::PhantomData<D>,
}

impl<D> FixedRank<D>
where
    D: Real,
{
    pub fn new(m: usize, n: usize, r: usize) -> Self {
        FixedRank {
            name: format!(
                "Fixed-rank manifold of {}x{} matrices with rank {}",
                m, n, r
            ),
            m,
            n,
            r,
            _marker: std::marker::PhantomData,
        }
    }

    fn point_factors(&self, point: &PointType<D>) -> (Array2<D>, Array1<D>, Array2<D>)
    where
        D: Scalar<Real = D> + ScalarOperand + Real + Lapack,
    {
        match point {
            PointType::Factorized { u, s, vt } => (u.clone(), s.clone(), vt.clone()),
            PointType::Full(mat) => tsvd(mat, self.r).unwrap(),
        }
    }

    fn is_point_factorized(&self, u: &Array2<D>, s: &Array1<D>, vt: &Array2<D>) -> bool
    where
        D: Scalar<Real = D> + ScalarOperand + Real + Lapack,
    {
        let eps = get_scalar_from_float::<D>(1e-8);
        if u.nrows() != self.m || u.ncols() != self.r {
            return false;
        }
        if vt.nrows() != self.r || vt.ncols() != self.n {
            return false;
        }
        if s.len() != self.r {
            return false;
        }
        let uu = u.t().dot(u);
        let vv = vt.dot(&vt.t());
        let i = Array2::<D>::eye(self.r);
        (&uu - &i).norm_l2() <= eps && (&vv - &i).norm_l2() <= eps
    }

    fn is_point_full(&self, x: &Array2<D>) -> bool
    where
        D: Scalar<Real = D> + ScalarOperand + Real + Lapack,
    {
        let eps = get_scalar_from_float::<D>(1e-8);
        if x.nrows() != self.m || x.ncols() != self.n {
            return false;
        }
        let s = x.svd(false, false).unwrap().1;
        let rank = s.iter().filter(|&&si| si > eps).count();
        rank == self.r
    }

    fn tangent_factors(
        &self,
        point: &PointType<D>,
        tangent_vector: &TangentVectorType<D>,
    ) -> (Array2<D>, Array2<D>, Array2<D>)
    where
        D: Scalar<Real = D> + ScalarOperand + Real + Lapack,
    {
        match tangent_vector {
            TangentVectorType::Factorized { up, m, vp } => (up.clone(), m.clone(), vp.clone()),
            TangentVectorType::Full(z) => match self.projection_from_ambient_full(point, z) {
                TangentVectorType::Factorized { up, m, vp } => (up, m, vp),
                TangentVectorType::Full(_) => {
                    unreachable!("projection should return a factorized tangent")
                }
            },
        }
    }

    fn apply_ambient(&self, vector: &AmbientType<D>, matrix: &Array2<D>) -> Array2<D>
    where
        D: Scalar + ScalarOperand,
    {
        match vector {
            AmbientType::Full(z) => z.dot(matrix),
            AmbientType::Factorized { u, s, v } => u.dot(s).dot(&v.t().dot(matrix)),
        }
    }

    fn apply_ambient_transpose(&self, vector: &AmbientType<D>, matrix: &Array2<D>) -> Array2<D>
    where
        D: Scalar + ScalarOperand,
    {
        match vector {
            AmbientType::Full(z) => z.t().dot(matrix),
            AmbientType::Factorized { u, s, v } => v.dot(&s.t().dot(&u.t().dot(matrix))),
        }
    }

    pub fn svd_back(u: &Array2<D>, s: &Array1<D>, vt: &Array2<D>) -> Array2<D> {
        let s_matrix = Array::from_diag(s);
        u.dot(&s_matrix).dot(vt)
    }

    pub fn embedding(
        &self,
        point: &PointType<D>,
        tangent_vector: &TangentVectorType<D>,
    ) -> AmbientType<D>
    where
        D: Scalar<Real = D> + ScalarOperand + Real + Lapack,
    {
        let (u, _s, vt) = self.point_factors(point);
        let (up, m, vp) = self.tangent_factors(point, tangent_vector);
        let full = u.dot(&m).dot(&vt) + up.dot(&vt) + u.dot(&vp.t());
        AmbientType::Full(full)
    }

    pub fn to_tangent_space(
        &self,
        point: &PointType<D>,
        tangent_vector: &TangentVectorType<D>,
    ) -> TangentVectorType<D>
    where
        D: Scalar<Real = D> + ScalarOperand + Real + Lapack,
    {
        let (u, _s, vt) = self.point_factors(point);
        let (up, m, vp) = self.tangent_factors(point, tangent_vector);
        let up_tan = &up - &u.dot(&u.t().dot(&up));
        let v = vt.t().to_owned();
        let vp_tan = &vp - &v.dot(&v.t().dot(&vp));
        TangentVectorType::Factorized {
            up: up_tan,
            m,
            vp: vp_tan,
        }
    }

    pub fn transport(
        &self,
        point_a: &PointType<D>,
        point_b: &PointType<D>,
        tangent_vector_a: &TangentVectorType<D>,
    ) -> TangentVectorType<D>
    where
        D: Scalar<Real = D> + ScalarOperand + Real + Lapack,
    {
        let embedded = self.embedding(point_a, tangent_vector_a);
        self.projection(point_b, &embedded)
    }

    pub fn zero_vector(&self) -> TangentVectorType<D>
    where
        D: Scalar + ScalarOperand,
    {
        TangentVectorType::Factorized {
            up: Array2::zeros((self.m, self.r)),
            m: Array2::zeros((self.r, self.r)),
            vp: Array2::zeros((self.n, self.r)),
        }
    }

    fn projection_core(
        &self,
        point: &PointType<D>,
        ambient_vector: &AmbientType<D>,
    ) -> TangentVectorType<D>
    where
        D: Scalar<Real = D> + ScalarOperand + Real + Lapack,
    {
        let (u, _s, vt) = self.point_factors(point);
        let z_v = self.apply_ambient(ambient_vector, &vt.t().to_owned());
        let ut_z_v = u.t().dot(&z_v);
        let zt_u = self.apply_ambient_transpose(ambient_vector, &u);

        let up = z_v - u.dot(&ut_z_v);
        let m = ut_z_v;
        let vp = zt_u - vt.t().dot(&m.t());
        TangentVectorType::Factorized { up, m, vp }
    }

    fn projection_from_ambient_full(
        &self,
        point: &PointType<D>,
        z: &Array2<D>,
    ) -> TangentVectorType<D>
    where
        D: Scalar<Real = D> + ScalarOperand + Real + Lapack,
    {
        self.projection_core(point, &AmbientType::Full(z.clone()))
    }

    fn projection_from_ambient_factorized(
        &self,
        point: &PointType<D>,
        u: &Array2<D>,
        s: &Array2<D>,
        v: &Array2<D>,
    ) -> TangentVectorType<D>
    where
        D: Scalar<Real = D> + ScalarOperand + Real + Lapack,
    {
        self.projection_core(
            point,
            &AmbientType::Factorized {
                u: u.clone(),
                s: s.clone(),
                v: v.clone(),
            },
        )
    }

    fn is_tangent_factorized(&self, point: &PointType<D>, up: &Array2<D>, vp: &Array2<D>) -> bool
    where
        D: Scalar<Real = D> + ScalarOperand + Real + Lapack,
    {
        let eps = get_scalar_from_float::<D>(1e-8);
        let (u, _s, vt) = self.point_factors(point);
        let c1 = up.t().dot(&u).norm_l2() <= eps;
        let c2 = vp.t().dot(&vt.t()).norm_l2() <= eps;
        c1 && c2
    }

    fn is_tangent_full(&self, point: &PointType<D>, z: &Array2<D>) -> bool
    where
        D: Scalar<Real = D> + ScalarOperand + Real + Lapack,
    {
        let eps = get_scalar_from_float::<D>(1e-8);
        let pz = self.projection_from_ambient_full(point, z);
        match pz {
            TangentVectorType::Factorized { up, m, vp } => {
                let z_proj = self.embedding(point, &TangentVectorType::Factorized { up, m, vp });
                if let AmbientType::Full(zp) = z_proj {
                    (z - zp).norm_l2() <= eps
                } else {
                    false
                }
            }
            TangentVectorType::Full(_) => false,
        }
    }

    fn retraction_factorized(
        &self,
        u: &Array2<D>,
        s: &Array1<D>,
        vt: &Array2<D>,
        up: &Array2<D>,
        m: &Array2<D>,
        vp: &Array2<D>,
    ) -> PointType<D>
    where
        D: Scalar<Real = D> + ScalarOperand + Real + Lapack,
    {
        let (_qu, ru) = up.qr().unwrap();
        let (qv, rv) = vp.qr().unwrap();

        let uu = ndarray::concatenate![Axis(1), u.view(), up.view()];
        let qu = qr(&uu).unwrap();
        let vv = ndarray::concatenate![Axis(1), vt.t().view(), qv.view()];

        let top = ndarray::concatenate![Axis(1), Array::from_diag(s) + m, rv.t().to_owned()];
        let bottom = ndarray::concatenate![Axis(1), ru, Array::zeros((self.r, self.r))];
        let t = ndarray::concatenate![Axis(0), top, bottom];

        let (ut, st, vtt) = t.svd(true, true).unwrap();
        let ut = ut.unwrap();
        let vtt = vtt.unwrap();

        let u_new = qu.dot(&ut.slice(s![.., ..self.r]).to_owned());
        let s_new = st.slice(s![..self.r]).to_owned() + D::epsilon();
        let v_new = vv.dot(&vtt.t().slice(s![.., ..self.r]).to_owned());
        PointType::Factorized {
            u: u_new,
            s: s_new,
            vt: v_new.t().to_owned(),
        }
    }

    fn inner_factorized(
        &self,
        up1: &Array2<D>,
        m1: &Array2<D>,
        vp1: &Array2<D>,
        up2: &Array2<D>,
        m2: &Array2<D>,
        vp2: &Array2<D>,
    ) -> D
    where
        D: Scalar,
    {
        up1.inner(up2) + m1.inner(m2) + vp1.inner(vp2)
    }

    fn ehess_to_rhess_core(
        &self,
        point: &PointType<D>,
        ehess: &AmbientType<D>,
    ) -> TangentVectorType<D>
    where
        D: Scalar<Real = D> + ScalarOperand + Real + Lapack,
    {
        self.projection_core(point, ehess)
    }
}

impl<D> Manifold for FixedRank<D>
where
    D: Scalar<Real = D> + ScalarOperand + Real + Lapack,
{
    type Point = PointType<D>;
    type TangentVector = TangentVectorType<D>;
    type AmbientPoint = AmbientType<D>;
    type Field = D;

    // fn is_point_on_manifold(&self, point: &Self::Point) -> bool {
    //     match point {
    //         PointType::Factorized { u, s, vt } => self.is_point_factorized(u, s, vt),
    //         PointType::Full(x) => self.is_point_full(x),
    //     }
    // }

    // fn is_tangent_vector(&self, point: &Self::Point, tangent_vector: &Self::TangentVector) -> bool {
    //     match tangent_vector {
    //         TangentVectorType::Factorized { up, m: _, vp } => {
    //             self.is_tangent_factorized(point, up, vp)
    //         }
    //         TangentVectorType::Full(z) => self.is_tangent_full(point, z),
    //     }
    // }

    fn base_point(&self) -> Self::Point {
        todo!()
    }

    fn inner(
        &self,
        point: &Self::Point,
        tangent_vector1: &Self::TangentVector,
        tangent_vector2: &Self::TangentVector,
    ) -> D {
        match (tangent_vector1, tangent_vector2) {
            (
                TangentVectorType::Factorized {
                    up: up1,
                    m: m1,
                    vp: vp1,
                },
                TangentVectorType::Factorized {
                    up: up2,
                    m: m2,
                    vp: vp2,
                },
            ) => self.inner_factorized(up1, m1, vp1, up2, m2, vp2),
            _ => {
                let (up1, m1, vp1) = self.tangent_factors(point, tangent_vector1);
                let (up2, m2, vp2) = self.tangent_factors(point, tangent_vector2);
                self.inner_factorized(&up1, &m1, &vp1, &up2, &m2, &vp2)
            }
        }
    }

    fn retraction(&self, point: &Self::Point, tangent_vector: &Self::TangentVector) -> Self::Point {
        let (u, s, vt) = self.point_factors(point);
        let (up, m, vp) = self.tangent_factors(point, tangent_vector);
        self.retraction_factorized(&u, &s, &vt, &up, &m, &vp)
    }

    fn projection(
        &self,
        point: &Self::Point,
        ambient_vector: &Self::AmbientPoint,
    ) -> Self::TangentVector {
        match ambient_vector {
            AmbientType::Full(z) => self.projection_from_ambient_full(point, z),
            AmbientType::Factorized { u, s, v } => {
                self.projection_from_ambient_factorized(point, u, s, v)
            }
        }
    }

    fn egrad_to_rgrad(
        &self,
        point: &Self::Point,
        egrad: &Self::AmbientPoint,
    ) -> Self::TangentVector {
        self.projection(point, egrad)
    }

    fn ehess_to_rhess(
        &self,
        point: &Self::Point,
        _tangent_vector: &Self::TangentVector,
        _egrad: &Self::AmbientPoint,
        ehess: &Self::AmbientPoint,
    ) -> Self::TangentVector {
        match ehess {
            AmbientType::Full(z) => self.ehess_to_rhess_core(point, &AmbientType::Full(z.clone())),
            AmbientType::Factorized { u, s, v } => self.ehess_to_rhess_core(
                point,
                &AmbientType::Factorized {
                    u: u.clone(),
                    s: s.clone(),
                    v: v.clone(),
                },
            ),
        }
    }
}

impl<D> RandomPoint for FixedRank<D>
where
    D: Scalar<Real = D> + ScalarOperand + Real + Lapack + SampleUniform,
{
    fn random_point(&self) -> Self::Point {
        let distribution = Uniform::new(
            get_scalar_from_float::<D>(0.),
            get_scalar_from_float::<D>(1.),
        )
        .unwrap();

        let q_u = qr(&Array2::random((self.m, self.r), &distribution)).unwrap();
        let q_v = qr(&Array2::random((self.n, self.r), &distribution)).unwrap();
        let mut s_vec = Array1::random(self.r, &distribution).to_vec();
        s_vec.sort_by(|a, b| b.partial_cmp(a).unwrap());
        let s = Array1::from_vec(s_vec);

        PointType::Factorized {
            u: q_u,
            s,
            vt: q_v.t().to_owned(),
        }
    }
}
