//! Built-in manifold implementations and manifold trait exports.

// pub mod fixed_rank; Generated by Copilot, not reviewed yet.
pub mod grassmann;
pub mod manifold;
pub mod sphere;
pub mod stiefel;

// pub use fixed_rank::FixedRank;
pub use grassmann::Grassmann;
pub use manifold::{Manifold, EGradToRGrad, EHessToRHess, RandomPoint, RandomTangentVector};
pub use sphere::Sphere;
pub use stiefel::Stiefel;
